const ShopActionTypes = {
    FETCH_COLLETIONS_START: "FETCH_COLLETIONS_START",
    FETCH_COLLETIONS_SUCCESS: "FETCH_COLLETIONS_SUCCESS",
    FETCH_COLLETIONS_FAILURE: "FETCH_COLLETIONS_FAILURE"
}

export default ShopActionTypes;